/**
 * Server-side Web Push utility — wraps the `web-push` npm library.
 *
 * Responsibilities:
 *   - Configure web-push with VAPID keys + subject (once, lazily)
 *   - Expose `sendPushNotification(subscription, payload)` that:
 *       * sends a push via the Web Push protocol (VAPID-signed)
 *       * returns success/failure
 *       * on 410 Gone / 404 (subscription expired), marks for cleanup
 *
 * Used by:
 *   - /api/admin/orders PATCH (admin changes status) → customer push
 *   - /api/telegram/webhook (Telegram inline button changes status) → customer push
 *   - /api/orders POST (new order created) → admin push
 *
 * VAPID keys come from env vars (VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY,
 * VAPID_SUBJECT). The keys were pre-generated by the project owner and
 * reused — DO NOT regenerate them, or every existing subscription will
 * become invalid.
 */

import webpush from "web-push";
import { db } from "@/lib/db";

let _configured = false;

function ensureConfigured() {
  if (_configured) return;
  const publicKey = process.env.VAPID_PUBLIC_KEY;
  const privateKey = process.env.VAPID_PRIVATE_KEY;
  const subject =
    process.env.VAPID_SUBJECT || "mailto:admin@shankar-sweets.local";

  if (!publicKey || !privateKey) {
    throw new Error(
      "[push] VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY env vars not set. " +
        "Push notifications cannot be sent."
    );
  }

  webpush.setVapidDetails(subject, publicKey, privateKey);
  _configured = true;
}

export type PushSubscriptionRow = {
  id: string;
  role: string; // "CUSTOMER" | "ADMIN"
  orderId: string | null;
  endpoint: string;
  p256dhKey: string;
  authKey: string;
};

export type PushPayload = {
  title: string;
  body: string;
  /** Optional deep-link URL — tapping the notification opens this in the app. */
  url?: string;
  /** Optional data payload (e.g. orderId, status) for the SW notificationclick. */
  data?: Record<string, unknown>;
  /** Optional tag — used to replace a previous notification with the same tag. */
  tag?: string;
  /** Optional icon URL (absolute path) — falls back to default in the SW. */
  icon?: string;
  /** Optional badge URL (Android only — small monochrome icon). */
  badge?: string;
};

/**
 * Send a single push notification to a single subscription.
 * Returns true on success, false on failure.
 *
 * On 410 (Gone) or 404 (Not Found), the subscription is expired/invalid
 * and is deleted from the DB so we don't keep trying.
 */
export async function sendPushNotification(
  subscription: PushSubscriptionRow,
  payload: PushPayload
): Promise<boolean> {
  ensureConfigured();

  // Web Push requires the subscription object in this exact shape.
  const pushSubscription = {
    endpoint: subscription.endpoint,
    keys: {
      p256dh: subscription.p256dhKey,
      auth: subscription.authKey,
    },
  };

  try {
    await webpush.sendNotification(
      pushSubscription,
      // Payload must be a string. JSON.stringify is the standard pattern.
      JSON.stringify(payload),
      {
        TTL: 60 * 60 * 24, // 24h — drop the notification if not delivered within 24h
        urgency: "normal",
        topic: payload.tag, // allows the SW to coalesce notifications with the same tag
      }
    );
    return true;
  } catch (err: any) {
    const status = err?.statusCode;
    // 404 = subscription expired
    // 410 = subscription unsubscribed/invalid
    // Both are non-recoverable → delete the subscription from the DB.
    if (status === 404 || status === 410) {
      try {
        await db.pushSubscription.delete({ where: { id: subscription.id } });
        console.log(
          `[push] subscription ${subscription.id} expired (status ${status}) — removed from DB`
        );
      } catch (e) {
        // Already deleted (e.g. parallel cleanup) — ignore
      }
      return false;
    }
    // 429 = rate limited — keep the subscription, just log
    // Other 4xx/5xx — log and don't delete; might be transient
    console.error(
      `[push] send failed for subscription ${subscription.id} (status ${status}):`,
      err?.message || err
    );
    return false;
  }
}

/**
 * Send a push notification to ALL subscriptions matching a filter
 * (e.g. all subscriptions for a given orderId, or all ADMIN subscriptions).
 *
 * Returns the number of successful deliveries.
 */
export async function broadcastPush(
  filter: { role?: string; orderId?: string },
  payload: PushPayload
): Promise<{ sent: number; failed: number }> {
  const subs = await db.pushSubscription.findMany({ where: filter });
  if (subs.length === 0) return { sent: 0, failed: 0 };

  const results = await Promise.allSettled(
    subs.map((s) => sendPushNotification(s as PushSubscriptionRow, payload))
  );

  let sent = 0;
  let failed = 0;
  for (const r of results) {
    if (r.status === "fulfilled" && r.value === true) {
      sent++;
    } else {
      failed++;
    }
  }
  return { sent, failed };
}

/**
 * Cleanup helper — called after an order is DELIVERED or after 30 days
 * since creation. Removes all CUSTOMER subscriptions tied to that order.
 */
export async function cleanupOrderSubscriptions(orderId: string): Promise<void> {
  try {
    await db.pushSubscription.deleteMany({ where: { orderId, role: "CUSTOMER" } });
  } catch (e) {
    // Best-effort cleanup — don't throw on failure
    console.error(`[push] cleanup failed for order ${orderId}:`, (e as Error).message);
  }
}
